### ISSUE TITLE
NPE thrown when testResultsDir configured incorrectly.

### ISSUE THREAD

**Issue by BillAtPros** [kncept/junit-reporter#7]
Caused by: java.lang.NullPointerException
        at com.kncept.junit5.reporter.gradle.TestHTMLReporterPluginTask.generateJunitReport(TestHTMLReporterPluginTask.java:46)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

It would be nice to have an error message indicating what's missing, instead of an NPE stack.

**Comment by nkrul** [comment]
Changed to a FileNotFound exception with a useful message.
Will be released in 1.0.3
